### ISSUE TITLE
Proxy to endpoints without auth is broken

### ISSUE THREAD

**Issue by ghost** [pwasem/ui5-middleware-http-proxy#6]
Right now you cannot proxy to static resources (like https://sapui5.hana.ondemand.com/resources).

request.js has a line which checks if auth is present

```
if (options.auth) {
```

Your latest change initializes auth with `{}` instead of `null`.

This results in the following error

info ui5-middleware-http-proxy GET /sap-ui-core.js -> https://sapui5.hana.ondemand.com/1.71.27/resources/sap-ui-core.js
Error: no auth mechanism defined
    at Auth.onRequest (...\node_modules\.pnpm\request@2.88.2\node_modules\request\lib\auth.js:132:32)
    at Request.auth (...\node_modules\.pnpm\request@2.88.2\node_modules\request\request.js:1344:14)
    at Request.init (...\node_modules\.pnpm\request@2.88.2\node_modules\request\request.js:381:10)

**Comment by pwasem** [comment]
@OTTOxMarc thanks for reporting!
This should be fixed with https://github.com/pwasem/ui5-middleware-http-proxy/pull/8 v.1.1.1
